### PR TITLE
cni and heapster are added to hyperkube

### PR DESCRIPTION
**Pull request by batikanu**
Inital example of the fork solution.
Cni settings are added to hyperkube Dockerfile
Heapster yaml files are included in addons. 

cc @cheld @zreigz @taimir

### CODE REVIEW

**Comment by cheld** [comment]
LGTM

**Comment by zreigz** [comment]
Your branch is very old: 718 commits behind kubernetes:master
Please rebase it

**Comment by cheld** [comment]
Well, we should rebase to released version, e.g. 1.3 - not master

**Comment by batikanu** [comment]
I created it from fujitsu master. We can update fujitsu master any version after merging.

**Pull request merged**
